spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: user-service-public
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/users/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: user-service-cb
                    statusCode: 503

            - id: user-service-internal
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/users/internal/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: user-service-cb
                    statusCode: 503

            - id: project-service-public
              uri: lb://PROJECT-SERVICE
              predicates:
                - Path=/api/projects/**, /api/tags/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: project-service-cb
                    statusCode: 503

            - id: project-service-internal
              uri: lb://PROJECT-SERVICE
              predicates:
                - Path=/api/projects/internal/**, /api/tags/internal/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: project-service-cb
                    statusCode: 503

            - id: task-service-public
              uri: lb://TASK-SERVICE
              predicates:
                - Path=/api/tasks/**, /api/comments/**, /api/task-tags/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: task-service-cb
                    statusCode: 503

            - id: task-service-internal
              uri: lb://TASK-SERVICE
              predicates:
                - Path=/api/tasks/internal/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: task-service-cb
                    statusCode: 503

            # === OpenAPI документация ===
            - id: user-openapi-root
              uri: lb://USER-SERVICE
              predicates:
                - Path=/v3/api-docs/user-service
              filters:
                - RewritePath=/v3/api-docs/user-service,/v3/api-docs-user

            - id: user-openapi-subpaths
              uri: lb://USER-SERVICE
              predicates:
                - Path=/v3/api-docs/user-service/**
              filters:
                - RewritePath=/v3/api-docs/user-service/(?<segment>.*),/v3/api-docs-user/${segment}

            - id: project-openapi-root
              uri: lb://PROJECT-SERVICE
              predicates:
                - Path=/v3/api-docs/project-service
              filters:
                - RewritePath=/v3/api-docs/project-service,/v3/api-docs-project

            - id: project-openapi-subpaths
              uri: lb://PROJECT-SERVICE
              predicates:
                - Path=/v3/api-docs/project-service/**
              filters:
                - RewritePath=/v3/api-docs/project-service/(?<segment>.*),/v3/api-docs-project/${segment}

            - id: task-openapi-root
              uri: lb://TASK-SERVICE
              predicates:
                - Path=/v3/api-docs/task-service
              filters:
                - RewritePath=/v3/api-docs/task-service,/v3/api-docs-task

            - id: task-openapi-subpaths
              uri: lb://TASK-SERVICE
              predicates:
                - Path=/v3/api-docs/task-service/**
              filters:
                - RewritePath=/v3/api-docs/task-service/(?<segment>.*),/v3/api-docs-task/${segment}

resilience4j:
  circuitbreaker:
    instances:
      user-service-cb:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        slowCallDurationThreshold: 2s
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
      project-service-cb:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        slowCallDurationThreshold: 2s
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
      task-service-cb:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        slowCallDurationThreshold: 2s
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

server:
  port: ${API_GATEWAY_PORT:8080}

springdoc:
  swagger-ui:
    urls:
      - name: User Service
        url: /v3/api-docs/user-service
      - name: Project Service
        url: /v3/api-docs/project-service
      - name: Task Service
        url: /v3/api-docs/task-service
    urls-primary-name: User Service
  override-with-gateway-url: true