spring:
  application:
    name: project-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:colabadb}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

eureka:
  instance:
    hostname: project-service
    prefer-ip-address: false

server:
  port: ${PROJECT_SERVICE_PORT:8082}

springdoc:
  api-docs:
    path: /v3/api-docs-project
  swagger-ui:
    config-url: /v3/api-docs-project/swagger-config
    url: /v3/api-docs-project
    urls:
      - url: /v3/api-docs-project
        name: Project Service API
  packages-to-scan: com.example.colaba.project.controller
