spring:
  application:
    name: project-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:colabadb}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

server:
  port: ${PROJECT_SERVICE_PORT:8082}

springdoc:
  packages-to-scan: com.example.colaba.controller
