spring:
  application:
    name: project-service

  datasource:
    url: jdbc:postgresql://${spring.db.host}:${spring.db.port}/${spring.db.name}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

server:
  port: ${PROJECT_SERVICE_PORT:8082}

springdoc:
  packages-to-scan: com.example.colaba.controller
