spring:
  application:
    name: task-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:colabadb}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

server:
  port: ${TASK_SERVICE_PORT:8083}

springdoc:
  packages-to-scan: com.example.colaba.task.controller
