spring:
  application:
    name: task-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:colabadb}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

  cloud:
    openfeign:
      client:
        config:
          user-service:
            connectTimeout: 1000
            readTimeout: 1000

resilience4j:
  circuitbreaker:
    instances:
      userClient:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 2s
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
      projectClient:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 2s
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        slidingWindowSize: 10

feign:
  client:
    config:
      default:
        connect-timeout: 1000
        read-timeout: 1000
        logger-level: basic
        error-decoder: com.example.colaba.shared.feign.FeignErrorDecoder
  circuitbreaker:
    enabled: true

eureka:
  instance:
    hostname: task-service
    prefer-ip-address: false

server:
  port: ${TASK_SERVICE_PORT:8083}

springdoc:
  api-docs:
    path: /v3/api-docs-task
  swagger-ui:
    config-url: /v3/api-docs-task/swagger-config
    url: /v3/api-docs-task
    urls:
      - url: /v3/api-docs-task
        name: Task Service API
  packages-to-scan: com.example.colaba.task.controller
