spring:
  application:
    name: task-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${TASK_DB_NAME:task_db}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

resilience4j:
  circuitbreaker:
    instances:
      user-service:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
      project-service:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    hostname: task-service
    prefer-ip-address: false

server:
  port: 0

springdoc:
  api-docs:
    path: /v3/api-docs-task
  swagger-ui:
    config-url: /v3/api-docs-task/swagger-config
    url: /v3/api-docs-task
    urls:
      - url: /v3/api-docs-task
        name: Task Service API
  packages-to-scan: com.example.colaba.task.infrastructure.controller
