spring:
  application:
    name: task-service

  datasource:
    url: jdbc:postgresql://${spring.db.host}:${spring.db.port}/${spring.db.name}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

server:
  port: ${TASK_SERVICE_PORT:8083}

springdoc:
  packages-to-scan: com.example.colaba.task.controller
