spring:
  application:
    name: task-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:colabadb}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

eureka:
  instance:
    hostname: task-service
    prefer-ip-address: false

server:
  port: ${TASK_SERVICE_PORT:8083}

springdoc:
  api-docs:
    path: /v3/api-docs-task
  swagger-ui:
    config-url: /v3/api-docs-task/swagger-config
    url: /v3/api-docs-task
    urls:
      - url: /v3/api-docs-task
        name: Task Service API
  packages-to-scan: com.example.colaba.task.controller
