spring:
  application:
    name: user-service

  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:colabadb}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

  liquibase:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:colabadb}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

eureka:
  instance:
    hostname: user-service
    prefer-ip-address: false

server:
  port: ${USER_SERVICE_PORT:8081}

springdoc:
  packages-to-scan: com.example.colaba.user.controller
