spring:
  application:
    name: user-service

  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:colabadb}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

  liquibase:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:colabadb}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

resilience4j:
  circuitbreaker:
    instances:
      taskClient:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 2s
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
      projectClient:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 2s
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        slidingWindowSize: 10

feign:
  client:
    config:
      default:
        connect-timeout: 1000
        read-timeout: 1000
        logger-level: basic
        error-decoder: com.example.colaba.shared.feign.FeignErrorDecoder
  circuitbreaker:
    enabled: true

eureka:
  instance:
    hostname: user-service
    prefer-ip-address: false

server:
  port: ${USER_SERVICE_PORT:8081}

springdoc:
  api-docs:
    path: /v3/api-docs-user
  swagger-ui:
    config-url: /v3/api-docs-user/swagger-config
    url: /v3/api-docs-user
    urls:
      - url: /v3/api-docs-user
        name: User Service API
  packages-to-scan: com.example.colaba.user.controller
